// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: user.sql

package queries

import (
	"context"
)

const getUserByUserId = `-- name: GetUserByUserId :one
SELECT id, username, password, created_at FROM ` + "`" + `user` + "`" + ` WHERE id = ?
`

func (q *Queries) GetUserByUserId(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserId, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
